1 hf3 nf9 b
ultrapotros/christmas-project pull request #16
Opened 2022-01-12 05:24 UTC by ultrapotros

Only header updated

2022-01-12 05:30 UTC, ultrapotros commented
El conflicto es solo el nombre del header, cuando reviséis ya lo cambio y hago el merge.

2022-01-12 08:34 UTC, maestre7 requested changes
has probado eso pq sino veo mal te estas cargando las import single category y product

2022-01-13 17:44 UTC, sMartz1 requested changes
Aqui hay que tener cuidado porque se borra la importación de dos componentes.

2022-01-13 20:19 UTC, sMartz1 approved these changes

2022-01-14 02:16 UTC, maestre7 reviewed
Has probado eso pq a mi me salen un montón de petardazos cuando arranco, revisa la consola del navegador que sino me confundo son dependencias de tabs.
Y aprovecha si puedes hecha un ojo a las indentaciones.
Muchas gracias y perdona las molestias.

2022-01-14 08:12 UTC, ultrapotros commented
> Has probado eso pq a mi me salen un montón de petardazos cuando arranco, revisa la consola del navegador que sino me confundo son dependencias de tabs. Y aprovecha si puedes hecha un ojo a las indentaciones. Muchas gracias y perdona las molestias.

Ya lo he visto que da unos warnings, la verdad es que no se como  arreglarlos, son nombres de atributos que crea en camelcase y le dice que todo en minúsculas. De todas formas a ver si termino el resto y quería hacer un menu hamburger como dijo Sebastián.

2022-01-15 17:31 UTC, ultrapotros commented
Ya están reparados los errores e implementado el menu hamburger, yo lo veo bien aunque para gustos están los colores. 
Los errores eran el componente de la librería, al final lo he hecho todo manual y solo uso la librería para los iconos.
También he añadido los 'p' que faltaban en el privacy que es una tontería.

2022-01-16 14:54 UTC, merged